export function seedDatabase(firebase) {
  // const week_14_form_submissions = [
  //   {
  //     username: "El Primo",
  //     "Steelers (6-5-1) @ Vikings (5-7)": "Vikings",
  //     "Cowboys (8-4) @ Washington (6-6)": "Cowboys",
  //     "Jaguars (2-10) @ Titans (8-4)": "Titans",
  //     "Seahawks (4-8) @ Texans (2-10)": "Seahawks",
  //     "Raiders (6-6) @ Chiefs (8-4)": "Chiefs",
  //     "Saints (5-7) @ Jets (3-9)": "Saints",
  //     "Falcons (5-7) @ Panthers (5-7)": "Panthers",
  //     "Ravens (8-4) @ Browns (6-6)": "Browns",
  //     "Giants (4-8) @ Chargers (7-5)": "Chargers",
  //     "Lions (1-10-1) @ Broncos (6-6)": "Broncos",
  //     "49ers (6-6) @ Bengals (7-5)": "Bengals",
  //     "Bills (7-5) @ Buccaneers (9-3)": "Bills",
  //     "Bears (4-8) @ Packers (9-3)": "Packers",
  //     "Rams (8-4) @ Cardinals (10-2)": "Rams",
  //     "Rams @ Cardinals Point Total": 51,
  //     "Email Address": "1herrerake@gmail.com",
  //     dateCreated: "12/9/2021 14:55:56",
  //   },
  //   {
  //     username: "Lachino",
  //     "Steelers (6-5-1) @ Vikings (5-7)": "Vikings",
  //     "Cowboys (8-4) @ Washington (6-6)": "Cowboys",
  //     "Jaguars (2-10) @ Titans (8-4)": "Titans",
  //     "Seahawks (4-8) @ Texans (2-10)": "Seahawks",
  //     "Raiders (6-6) @ Chiefs (8-4)": "Chiefs",
  //     "Saints (5-7) @ Jets (3-9)": "Saints",
  //     "Falcons (5-7) @ Panthers (5-7)": "Panthers",
  //     "Ravens (8-4) @ Browns (6-6)": "Ravens",
  //     "Giants (4-8) @ Chargers (7-5)": "Chargers",
  //     "Lions (1-10-1) @ Broncos (6-6)": "Broncos",
  //     "49ers (6-6) @ Bengals (7-5)": "Bengals",
  //     "Bills (7-5) @ Buccaneers (9-3)": "Buccaneers",
  //     "Bears (4-8) @ Packers (9-3)": "Packers",
  //     "Rams (8-4) @ Cardinals (10-2)": "Cardinals",
  //     "Rams @ Cardinals Point Total": 56,
  //     "Email Address": "ptep03@gmail.com",
  //     dateCreated: "12/9/2021 18:16:27",
  //   },
  //   {
  //     username: "Tmoney",
  //     "Steelers (6-5-1) @ Vikings (5-7)": "Vikings",
  //     "Cowboys (8-4) @ Washington (6-6)": "Washington",
  //     "Jaguars (2-10) @ Titans (8-4)": "Titans",
  //     "Seahawks (4-8) @ Texans (2-10)": "Seahawks",
  //     "Raiders (6-6) @ Chiefs (8-4)": "Chiefs",
  //     "Saints (5-7) @ Jets (3-9)": "Saints",
  //     "Falcons (5-7) @ Panthers (5-7)": "Falcons",
  //     "Ravens (8-4) @ Browns (6-6)": "Ravens",
  //     "Giants (4-8) @ Chargers (7-5)": "Chargers",
  //     "Lions (1-10-1) @ Broncos (6-6)": "Broncos",
  //     "49ers (6-6) @ Bengals (7-5)": "Bengals",
  //     "Bills (7-5) @ Buccaneers (9-3)": "Buccaneers",
  //     "Bears (4-8) @ Packers (9-3)": "Packers",
  //     "Rams (8-4) @ Cardinals (10-2)": "Cardinals",
  //     "Rams @ Cardinals Point Total": 56,
  //     "Email Address": "earojas003@gmail.com",
  //     dateCreated: "12/9/2021 16:27:22",
  //   },
  //   {
  //     username: "Salv",
  //     "Steelers (6-5-1) @ Vikings (5-7)": "Vikings",
  //     "Cowboys (8-4) @ Washington (6-6)": "Washington",
  //     "Jaguars (2-10) @ Titans (8-4)": "Titans",
  //     "Seahawks (4-8) @ Texans (2-10)": "Seahawks",
  //     "Raiders (6-6) @ Chiefs (8-4)": "Chiefs",
  //     "Saints (5-7) @ Jets (3-9)": "Saints",
  //     "Falcons (5-7) @ Panthers (5-7)": "Panthers",
  //     "Ravens (8-4) @ Browns (6-6)": "Ravens",
  //     "Giants (4-8) @ Chargers (7-5)": "Chargers",
  //     "Lions (1-10-1) @ Broncos (6-6)": "Broncos",
  //     "49ers (6-6) @ Bengals (7-5)": "49ers",
  //     "Bills (7-5) @ Buccaneers (9-3)": "Buccaneers",
  //     "Bears (4-8) @ Packers (9-3)": "Packers",
  //     "Rams (8-4) @ Cardinals (10-2)": "Cardinals",
  //     "Rams @ Cardinals Point Total": 53,
  //     "Email Address": "salvadorhernan33@yahoo.com",
  //     dateCreated: "12/9/2021 17:07:34",
  //   },
  //   {
  //     username: "SEL",
  //     "Steelers (6-5-1) @ Vikings (5-7)": "Steelers",
  //     "Cowboys (8-4) @ Washington (6-6)": "Washington",
  //     "Jaguars (2-10) @ Titans (8-4)": "Titans",
  //     "Seahawks (4-8) @ Texans (2-10)": "Seahawks",
  //     "Raiders (6-6) @ Chiefs (8-4)": "Chiefs",
  //     "Saints (5-7) @ Jets (3-9)": "Saints",
  //     "Falcons (5-7) @ Panthers (5-7)": "Panthers",
  //     "Ravens (8-4) @ Browns (6-6)": "Browns",
  //     "Giants (4-8) @ Chargers (7-5)": "Chargers",
  //     "Lions (1-10-1) @ Broncos (6-6)": "Broncos",
  //     "49ers (6-6) @ Bengals (7-5)": "Bengals",
  //     "Bills (7-5) @ Buccaneers (9-3)": "Buccaneers",
  //     "Bears (4-8) @ Packers (9-3)": "Packers",
  //     "Rams (8-4) @ Cardinals (10-2)": "Cardinals",
  //     "Rams @ Cardinals Point Total": 55,
  //     "Email Address": "selwinm@yahoo.com",
  //     dateCreated: "12/9/2021 17:05:21",
  //   },
  //   {
  //     username: "HP314",
  //     "Steelers (6-5-1) @ Vikings (5-7)": "Steelers",
  //     "Cowboys (8-4) @ Washington (6-6)": "Washington",
  //     "Jaguars (2-10) @ Titans (8-4)": "Titans",
  //     "Seahawks (4-8) @ Texans (2-10)": "Seahawks",
  //     "Raiders (6-6) @ Chiefs (8-4)": "Chiefs",
  //     "Saints (5-7) @ Jets (3-9)": "Saints",
  //     "Falcons (5-7) @ Panthers (5-7)": "Panthers",
  //     "Ravens (8-4) @ Browns (6-6)": "Ravens",
  //     "Giants (4-8) @ Chargers (7-5)": "Chargers",
  //     "Lions (1-10-1) @ Broncos (6-6)": "Broncos",
  //     "49ers (6-6) @ Bengals (7-5)": "49ers",
  //     "Bills (7-5) @ Buccaneers (9-3)": "Buccaneers",
  //     "Bears (4-8) @ Packers (9-3)": "Packers",
  //     "Rams (8-4) @ Cardinals (10-2)": "Cardinals",
  //     "Rams @ Cardinals Point Total": 45,
  //     "Email Address": "henry.portillo14@yahoo.com",
  //     dateCreated: "12/9/2021 15:46:43",
  //   },
  //   {
  //     username: "Lou",
  //     "Steelers (6-5-1) @ Vikings (5-7)": "Vikings",
  //     "Cowboys (8-4) @ Washington (6-6)": "Washington",
  //     "Jaguars (2-10) @ Titans (8-4)": "Titans",
  //     "Seahawks (4-8) @ Texans (2-10)": "Seahawks",
  //     "Raiders (6-6) @ Chiefs (8-4)": "Chiefs",
  //     "Saints (5-7) @ Jets (3-9)": "Jets",
  //     "Falcons (5-7) @ Panthers (5-7)": "Panthers",
  //     "Ravens (8-4) @ Browns (6-6)": "Ravens",
  //     "Giants (4-8) @ Chargers (7-5)": "Chargers",
  //     "Lions (1-10-1) @ Broncos (6-6)": "Broncos",
  //     "49ers (6-6) @ Bengals (7-5)": "Bengals",
  //     "Bills (7-5) @ Buccaneers (9-3)": "Buccaneers",
  //     "Bears (4-8) @ Packers (9-3)": "Packers",
  //     "Rams (8-4) @ Cardinals (10-2)": "Cardinals",
  //     "Rams @ Cardinals Point Total": 50,
  //     "Email Address": "l14_dc@hotmail.com",
  //     dateCreated: "12/9/2021 17:29:48",
  //   },
  // ];

  // const week_14_submissions_table = [
  //   {
  //     Game: "Steelers (6-5-1) @ Vikings (5-7)",
  //     "El Primo": "Vikings",
  //     Lachino: "Vikings",
  //     TMoney: "Vikings",
  //     Salv: "Vikings",
  //     SEL: "Steelers",
  //     HP314: "Steelers",
  //     Lou: "Vikings",
  //   },
  //   {
  //     Game: "Cowboys (8-4) @ Washington (6-6)",
  //     "El Primo": "Cowboys",
  //     Lachino: "Cowboys",
  //     TMoney: "Washington",
  //     Salv: "Washington",
  //     SEL: "Washington",
  //     HP314: "Washington",
  //     Lou: "Washington",
  //   },
  //   {
  //     Game: "Jaguars (2-10) @ Titans (8-4)",
  //     "El Primo": "Titans",
  //     Lachino: "Titans",
  //     TMoney: "Titans",
  //     Salv: "Titans",
  //     SEL: "Titans",
  //     HP314: "Titans",
  //     Lou: "Titans",
  //   },
  //   {
  //     Game: "Seahawks (4-8) @ Texans (2-10)",
  //     "El Primo": "Seahawks",
  //     Lachino: "Seahawks",
  //     TMoney: "Seahawks",
  //     Salv: "Seahawks",
  //     SEL: "Seahawks",
  //     HP314: "Seahawks",
  //     Lou: "Seahawks",
  //   },
  //   {
  //     Game: "Raiders (6-6) @ Chiefs (8-4)",
  //     "El Primo": "Chiefs",
  //     Lachino: "Chiefs",
  //     TMoney: "Chiefs",
  //     Salv: "Chiefs",
  //     SEL: "Chiefs",
  //     HP314: "Chiefs",
  //     Lou: "Chiefs",
  //   },
  //   {
  //     Game: "Saints (5-7) @ Jets (3-9)",
  //     "El Primo": "Saints",
  //     Lachino: "Saints",
  //     TMoney: "Saints",
  //     Salv: "Saints",
  //     SEL: "Saints",
  //     HP314: "Saints",
  //     Lou: "Jets",
  //   },
  //   {
  //     Game: "Falcons (5-7) @ Panthers (5-7)",
  //     "El Primo": "Panthers",
  //     Lachino: "Panthers",
  //     TMoney: "Falcons",
  //     Salv: "Panthers",
  //     SEL: "Panthers",
  //     HP314: "Panthers",
  //     Lou: "Panthers",
  //   },
  //   {
  //     Game: "Ravens (8-4) @ Browns (6-6)",
  //     "El Primo": "Browns",
  //     Lachino: "Ravens",
  //     TMoney: "Ravens",
  //     Salv: "Ravens",
  //     SEL: "Browns",
  //     HP314: "Ravens",
  //     Lou: "Ravens",
  //   },
  //   {
  //     Game: "Giants (4-8) @ Chargers (7-5)",
  //     "El Primo": "Chargers",
  //     Lachino: "Chargers",
  //     TMoney: "Chargers",
  //     Salv: "Chargers",
  //     SEL: "Chargers",
  //     HP314: "Chargers",
  //     Lou: "Chargers",
  //   },
  //   {
  //     Game: "Lions (1-10-1) @ Broncos (6-6)",
  //     "El Primo": "Broncos",
  //     Lachino: "Broncos",
  //     TMoney: "Broncos",
  //     Salv: "Broncos",
  //     SEL: "Broncos",
  //     HP314: "Broncos",
  //     Lou: "Broncos",
  //   },
  //   {
  //     Game: "49ers (6-6) @ Bengals (7-5)",
  //     "El Primo": "Bengals",
  //     Lachino: "Bengals",
  //     TMoney: "Bengals",
  //     Salv: "49ers",
  //     SEL: "Bengals",
  //     HP314: "49ers",
  //     Lou: "Bengals",
  //   },
  //   {
  //     Game: "Bills (7-5) @ Buccaneers (9-3)",
  //     "El Primo": "Bills",
  //     Lachino: "Buccaneers",
  //     TMoney: "Buccaneers",
  //     Salv: "Buccaneers",
  //     SEL: "Buccaneers",
  //     HP314: "Buccaneers",
  //     Lou: "Buccaneers",
  //   },
  //   {
  //     Game: "Bears (4-8) @ Packers (9-3)",
  //     "El Primo": "Packers",
  //     Lachino: "Packers",
  //     TMoney: "Packers",
  //     Salv: "Packers",
  //     SEL: "Packers",
  //     HP314: "Packers",
  //     Lou: "Packers",
  //   },
  //   {
  //     Game: "Rams (8-4) @ Cardinals (10-2)",
  //     "El Primo": "Rams",
  //     Lachino: "Cardinals",
  //     TMoney: "Cardinals",
  //     Salv: "Cardinals",
  //     SEL: "Cardinals",
  //     HP314: "Cardinals",
  //     Lou: "Cardinals",
  //   },
  //   {
  //     "Point Total": "Rams @ Cardinals Point Total",
  //     "El Primo": "51",
  //     Lachino: "56",
  //     TMoney: "56",
  //     Salv: "53",
  //     SEL: "55",
  //     HP314: "45",
  //     Lou: "50",
  //   },
  //   {
  //     final: "Least Ls",
  //     "El Primo": "3",
  //     Lachino: "4",
  //     TMoney: "4",
  //     Salv: "4",
  //     SEL: "5",
  //     HP314: "5",
  //     Lou: "6",
  //   },
  // ];

  // const week_13_form_submissions = [
  //   {
  //     username: "Lou",
  //     "Cowboys (7-4) @ Saints (5-6)": "Cowboys",
  //     "Giants (4-7) @ Dolphins (5-7)": "Dolphins",
  //     "Colts (6-6) @ Texans (2-9)": "Colts",
  //     "Vikings (5-6) @ Lions (0-10-1)": "Vikings",
  //     "Eagles (5-7) @ Jets (3-8)": "Eagles",
  //     "Cardinals (9-2) @ Bears (4-7)": "Cardinals",
  //     "Chargers (6-5) @ Bengals (7-4)": "Bengals",
  //     "Buccaneers (8-3) @ Falcons (5-6)": "Buccaneers",
  //     "Jaguars (2-9) @ Rams (7-4)": "Rams",
  //     "Washington (5-6) @ Raiders (6-5)": "Washington",
  //     "Ravens (8-3) @ Steelers (5-5-1)": "Ravens",
  //     "49ers (6-5) @ Seahawks (3-8)": "49ers",
  //     "Broncos (6-5) @ Chiefs (7-4)": "Chiefs",
  //     "Patriots (8-4) @ Bills (7-4)": "Patriots",
  //     "Patriots @ Bills Point Total (24)": 50,
  //     "Email Address": "L14_dc@hotmail.com",
  //     Timestamp: "12/1/2021 19:22:34",
  //   },
  //   {
  //     username: "TMoney",
  //     "Cowboys (7-4) @ Saints (5-6)": "Saints",
  //     "Giants (4-7) @ Dolphins (5-7)": "Dolphins",
  //     "Colts (6-6) @ Texans (2-9)": "Colts",
  //     "Vikings (5-6) @ Lions (0-10-1)": "Vikings",
  //     "Eagles (5-7) @ Jets (3-8)": "Eagles",
  //     "Cardinals (9-2) @ Bears (4-7)": "Cardinals",
  //     "Chargers (6-5) @ Bengals (7-4)": "Bengals",
  //     "Buccaneers (8-3) @ Falcons (5-6)": "Buccaneers",
  //     "Jaguars (2-9) @ Rams (7-4)": "Rams",
  //     "Washington (5-6) @ Raiders (6-5)": "Washington",
  //     "Ravens (8-3) @ Steelers (5-5-1)": "Ravens",
  //     "49ers (6-5) @ Seahawks (3-8)": "Seahawks",
  //     "Broncos (6-5) @ Chiefs (7-4)": "Chiefs",
  //     "Patriots (8-4) @ Bills (7-4)": "Patriots",
  //     "Patriots @ Bills Point Total (24)": 50,
  //     "Email Address": "earojas003@gmail.com",
  //     Timestamp: "12/2/2021 17:25:41",
  //   },
  //   {
  //     username: "Josev",
  //     "Cowboys (7-4) @ Saints (5-6)": "Cowboys",
  //     "Giants (4-7) @ Dolphins (5-7)": "Dolphins",
  //     "Colts (6-6) @ Texans (2-9)": "Colts",
  //     "Vikings (5-6) @ Lions (0-10-1)": "Vikings",
  //     "Eagles (5-7) @ Jets (3-8)": "Eagles",
  //     "Cardinals (9-2) @ Bears (4-7)": "Cardinals",
  //     "Chargers (6-5) @ Bengals (7-4)": "Bengals",
  //     "Buccaneers (8-3) @ Falcons (5-6)": "Buccaneers",
  //     "Jaguars (2-9) @ Rams (7-4)": "Rams",
  //     "Washington (5-6) @ Raiders (6-5)": "Raiders",
  //     "Ravens (8-3) @ Steelers (5-5-1)": "Ravens",
  //     "49ers (6-5) @ Seahawks (3-8)": "49ers",
  //     "Broncos (6-5) @ Chiefs (7-4)": "Chiefs",
  //     "Patriots (8-4) @ Bills (7-4)": "Patriots",
  //     "Patriots @ Bills Point Total (24)": 45,
  //     "Email Address": "jos3.villarro3l@gmail.com",
  //     Timestamp: "12/1/2021 10:17:47",
  //   },
  //   {
  //     username: "SEL",
  //     "Cowboys (7-4) @ Saints (5-6)": "Cowboys",
  //     "Giants (4-7) @ Dolphins (5-7)": "Dolphins",
  //     "Colts (6-6) @ Texans (2-9)": "Colts",
  //     "Vikings (5-6) @ Lions (0-10-1)": "Vikings",
  //     "Eagles (5-7) @ Jets (3-8)": "Eagles",
  //     "Cardinals (9-2) @ Bears (4-7)": "Cardinals",
  //     "Chargers (6-5) @ Bengals (7-4)": "Bengals",
  //     "Buccaneers (8-3) @ Falcons (5-6)": "Buccaneers",
  //     "Jaguars (2-9) @ Rams (7-4)": "Rams",
  //     "Washington (5-6) @ Raiders (6-5)": "Washington",
  //     "Ravens (8-3) @ Steelers (5-5-1)": "Ravens",
  //     "49ers (6-5) @ Seahawks (3-8)": "49ers",
  //     "Broncos (6-5) @ Chiefs (7-4)": "Chiefs",
  //     "Patriots (8-4) @ Bills (7-4)": "Bills",
  //     "Patriots @ Bills Point Total (24)": 42,
  //     "Email Address": "selwinm@yahoo.com",
  //     Timestamp: "12/2/2021 16:09:19",
  //   },
  //   {
  //     username: "Lachino",
  //     "Cowboys (7-4) @ Saints (5-6)": "Cowboys",
  //     "Giants (4-7) @ Dolphins (5-7)": "Dolphins",
  //     "Colts (6-6) @ Texans (2-9)": "Colts",
  //     "Vikings (5-6) @ Lions (0-10-1)": "Vikings",
  //     "Eagles (5-7) @ Jets (3-8)": "Eagles",
  //     "Cardinals (9-2) @ Bears (4-7)": "Cardinals",
  //     "Chargers (6-5) @ Bengals (7-4)": "Bengals",
  //     "Buccaneers (8-3) @ Falcons (5-6)": "Buccaneers",
  //     "Jaguars (2-9) @ Rams (7-4)": "Rams",
  //     "Washington (5-6) @ Raiders (6-5)": "Raiders",
  //     "Ravens (8-3) @ Steelers (5-5-1)": "Ravens",
  //     "49ers (6-5) @ Seahawks (3-8)": "49ers",
  //     "Broncos (6-5) @ Chiefs (7-4)": "Chiefs",
  //     "Patriots (8-4) @ Bills (7-4)": "Bills",
  //     "Patriots @ Bills Point Total (24)": 56,
  //     "Email Address": "ptep03@gmail.com",
  //     Timestamp: "11/30/2021 15:27:14",
  //   },
  //   {
  //     username: "Manzano",
  //     "Cowboys (7-4) @ Saints (5-6)": "Saints",
  //     "Giants (4-7) @ Dolphins (5-7)": "Dolphins",
  //     "Colts (6-6) @ Texans (2-9)": "Colts",
  //     "Vikings (5-6) @ Lions (0-10-1)": "Vikings",
  //     "Eagles (5-7) @ Jets (3-8)": "Eagles",
  //     "Cardinals (9-2) @ Bears (4-7)": "Cardinals",
  //     "Chargers (6-5) @ Bengals (7-4)": "Bengals",
  //     "Buccaneers (8-3) @ Falcons (5-6)": "Buccaneers",
  //     "Jaguars (2-9) @ Rams (7-4)": "Rams",
  //     "Washington (5-6) @ Raiders (6-5)": "Washington",
  //     "Ravens (8-3) @ Steelers (5-5-1)": "Ravens",
  //     "49ers (6-5) @ Seahawks (3-8)": "49ers",
  //     "Broncos (6-5) @ Chiefs (7-4)": "Chiefs",
  //     "Patriots (8-4) @ Bills (7-4)": "Bills",
  //     "Patriots @ Bills Point Total (24)": 48,
  //     "Email Address": "jomanzan13@gmail.com",
  //     Timestamp: "11/30/2021 23:04:36",
  //   },
  //   {
  //     username: "Odoylerules",
  //     "Cowboys (7-4) @ Saints (5-6)": "Cowboys",
  //     "Giants (4-7) @ Dolphins (5-7)": "Dolphins",
  //     "Colts (6-6) @ Texans (2-9)": "Colts",
  //     "Vikings (5-6) @ Lions (0-10-1)": "Vikings",
  //     "Eagles (5-7) @ Jets (3-8)": "Eagles",
  //     "Cardinals (9-2) @ Bears (4-7)": "Cardinals",
  //     "Chargers (6-5) @ Bengals (7-4)": "Bengals",
  //     "Buccaneers (8-3) @ Falcons (5-6)": "Buccaneers",
  //     "Jaguars (2-9) @ Rams (7-4)": "Rams",
  //     "Washington (5-6) @ Raiders (6-5)": "Raiders",
  //     "Ravens (8-3) @ Steelers (5-5-1)": "Ravens",
  //     "49ers (6-5) @ Seahawks (3-8)": "49ers",
  //     "Broncos (6-5) @ Chiefs (7-4)": "Broncos",
  //     "Patriots (8-4) @ Bills (7-4)": "Patriots",
  //     "Patriots @ Bills Point Total (24)": 46,
  //     "Email Address": "dannysorto1@icloud.com",
  //     Timestamp: "11/30/2021 15:36:43",
  //   },
  // ];

  // const week_13_submissions_table = [
  //   {
  //     game: "Cowboys (7-4) @ Saints (5-6)",
  //     Lou: "Cowboys",
  //     TMoney: "Saints",
  //     Josev: "Cowboys",
  //     SEL: "Cowboys",
  //     Lachino: "Cowboys",
  //     Manzano: "Saints",
  //     Odoylerules: "Cowboys",
  //   },
  //   {
  //     game: "Giants (4-7) @ Dolphins (5-7)",
  //     Lou: "Dolphins",
  //     TMoney: "Dolphins",
  //     Josev: "Dolphins",
  //     SEL: "Dolphins",
  //     Lachino: "Dolphins",
  //     Manzano: "Dolphins",
  //     Odoylerules: "Dolphins",
  //   },
  //   {
  //     game: "Colts (6-6) @ Texans (2-9)",
  //     Lou: "Colts",
  //     TMoney: "Colts",
  //     Josev: "Colts",
  //     SEL: "Colts",
  //     Lachino: "Colts",
  //     Manzano: "Colts",
  //     Odoylerules: "Colts",
  //   },
  //   {
  //     game: "Vikings (5-6) @ Lions (0-10-1)",
  //     Lou: "Vikings",
  //     TMoney: "Vikings",
  //     Josev: "Vikings",
  //     SEL: "Vikings",
  //     Lachino: "Vikings",
  //     Manzano: "Vikings",
  //     Odoylerules: "Vikings",
  //   },
  //   {
  //     game: "Eagles (5-7) @ Jets (3-8)",
  //     Lou: "Eagles",
  //     TMoney: "Eagles",
  //     Josev: "Eagles",
  //     SEL: "Eagles",
  //     Lachino: "Eagles",
  //     Manzano: "Eagles",
  //     Odoylerules: "Eagles",
  //   },
  //   {
  //     game: "Cardinals (9-2) @ Bears (4-7)",
  //     Lou: "Cardinals",
  //     TMoney: "Cardinals",
  //     Josev: "Cardinals",
  //     SEL: "Cardinals",
  //     Lachino: "Cardinals",
  //     Manzano: "Cardinals",
  //     Odoylerules: "Cardinals",
  //   },
  //   {
  //     game: "Chargers (6-5) @ Bengals (7-4)",
  //     Lou: "Bengals",
  //     TMoney: "Bengals",
  //     Josev: "Bengals",
  //     SEL: "Bengals",
  //     Lachino: "Bengals",
  //     Manzano: "Bengals",
  //     Odoylerules: "Bengals",
  //   },
  //   {
  //     game: "Buccaneers (8-3) @ Falcons (5-6)",
  //     Lou: "Buccaneers",
  //     TMoney: "Buccaneers",
  //     Josev: "Buccaneers",
  //     SEL: "Buccaneers",
  //     Lachino: "Buccaneers",
  //     Manzano: "Buccaneers",
  //     Odoylerules: "Buccaneers",
  //   },
  //   {
  //     game: "Jaguars (2-9) @ Rams (7-4)",
  //     Lou: "Rams",
  //     TMoney: "Rams",
  //     Josev: "Rams",
  //     SEL: "Rams",
  //     Lachino: "Rams",
  //     Manzano: "Rams",
  //     Odoylerules: "Rams",
  //   },
  //   {
  //     game: "Washington (5-6) @ Raiders (6-5)",
  //     Lou: "Washington",
  //     TMoney: "Washington",
  //     Josev: "Raiders",
  //     SEL: "Washington",
  //     Lachino: "Raiders",
  //     Manzano: "Washington",
  //     Odoylerules: "Raiders",
  //   },
  //   {
  //     game: "Ravens (8-3) @ Steelers (5-5-1)",
  //     Lou: "Ravens",
  //     TMoney: "Ravens",
  //     Josev: "Ravens",
  //     SEL: "Ravens",
  //     Lachino: "Ravens",
  //     Manzano: "Ravens",
  //     Odoylerules: "Ravens",
  //   },
  //   {
  //     game: "49ers (6-5) @ Seahawks (3-8)",
  //     Lou: "49ers",
  //     TMoney: "Seahawks",
  //     Josev: "49ers",
  //     SEL: "49ers",
  //     Lachino: "49ers",
  //     Manzano: "49ers",
  //     Odoylerules: "49ers",
  //   },
  //   {
  //     game: "Broncos (6-5) @ Chiefs (7-4)",
  //     Lou: "Chiefs",
  //     TMoney: "Chiefs",
  //     Josev: "Chiefs",
  //     SEL: "Chiefs",
  //     Lachino: "Chiefs",
  //     Manzano: "Chiefs",
  //     Odoylerules: "Broncos",
  //   },
  //   {
  //     game: "Patriots (8-4) @ Bills (7-4)",
  //     Lou: "Patriots",
  //     TMoney: "Patriots",
  //     Josev: "Patriots",
  //     SEL: "Bills",
  //     Lachino: "Bills",
  //     Manzano: "Bills",
  //     Odoylerules: "Patriots",
  //   },
  //   {
  //     "Point Total": "Patriots @ Bills Point Total (24)",
  //     Lou: "50",
  //     TMoney: "50",
  //     Josev: "45",
  //     SEL: "42",
  //     Lachino: "56",
  //     Manzano: "48",
  //     Odoylerules: "46",
  //   },
  //   {
  //     final: "Least Ls",
  //     Lou: "4",
  //     TMoney: "4",
  //     Josev: "5",
  //     SEL: "5",
  //     Lachino: "6",
  //     Manzano: "6",
  //     Odoylerules: "6",
  //   },
  // ];

  // const week_12_form_submissions = [
  //   {
  //     username: "Jay",
  //     "Bears (3-7) @ Lions (0-9-1)": "Bears",
  //     "Raiders (5-5) @ Cowboys (7-3)": "Raiders",
  //     "Bills (6-4) @ Saints (5-5)": "Bills",
  //     "Buccaneers (7-3) @ Colts (6-5)": "Buccaneers",
  //     "Jets (2-8) @ Texans (2-8)": "Texans",
  //     "Eagles (5-6) @ Giants (3-7)": "Eagles",
  //     "Panthers (5-6) @ Dolphins (4-7)": "Panthers",
  //     "Titans (8-3) @ Patriots (7-4)": "Patriots",
  //     "Steelers (5-4-1) @ Bengals (6-4)": "Steelers",
  //     "Falcons (4-6) @ Jaguars (2-8)": "Falcons",
  //     "Chargers (6-4) @ Broncos (5-5)": "Chargers",
  //     "Rams (7-3) @ Packers (8-3)": "Packers",
  //     "Vikings (5-5) @ 49ers (5-5)": "49ers",
  //     "Browns (6-5) @ Ravens (7-3)": "Ravens",
  //     "Seahawks (3-7) @ Washington (4-6)": "Washington",
  //     "Seahawks @ Washington Point Total": 45,
  //     Timestamp: "11/25/2021 1:51:57",
  //     "Email Address": "montanna76@gmail.com",
  //   },
  //   {
  //     username: "Henrock ",
  //     "Bears (3-7) @ Lions (0-9-1)": "Bears",
  //     "Raiders (5-5) @ Cowboys (7-3)": "Raiders",
  //     "Bills (6-4) @ Saints (5-5)": "Bills",
  //     "Buccaneers (7-3) @ Colts (6-5)": "Colts",
  //     "Jets (2-8) @ Texans (2-8)": "Texans",
  //     "Eagles (5-6) @ Giants (3-7)": "Eagles",
  //     "Panthers (5-6) @ Dolphins (4-7)": "Dolphins",
  //     "Titans (8-3) @ Patriots (7-4)": "Titans",
  //     "Steelers (5-4-1) @ Bengals (6-4)": "Bengals",
  //     "Falcons (4-6) @ Jaguars (2-8)": "Falcons",
  //     "Chargers (6-4) @ Broncos (5-5)": "Chargers",
  //     "Rams (7-3) @ Packers (8-3)": "Packers",
  //     "Vikings (5-5) @ 49ers (5-5)": "Vikings",
  //     "Browns (6-5) @ Ravens (7-3)": "Ravens",
  //     "Seahawks (3-7) @ Washington (4-6)": "Washington",
  //     "Seahawks @ Washington Point Total": 38,
  //     Timestamp: "11/24/2021 21:16:07",
  //     "Email Address": "requenohenry28@gmail.com",
  //   },
  //   {
  //     username: "Odoylerules",
  //     "Bears (3-7) @ Lions (0-9-1)": "Bears",
  //     "Raiders (5-5) @ Cowboys (7-3)": "Cowboys",
  //     "Bills (6-4) @ Saints (5-5)": "Bills",
  //     "Buccaneers (7-3) @ Colts (6-5)": "Buccaneers",
  //     "Jets (2-8) @ Texans (2-8)": "Texans",
  //     "Eagles (5-6) @ Giants (3-7)": "Eagles",
  //     "Panthers (5-6) @ Dolphins (4-7)": "Panthers",
  //     "Titans (8-3) @ Patriots (7-4)": "Patriots",
  //     "Steelers (5-4-1) @ Bengals (6-4)": "Steelers",
  //     "Falcons (4-6) @ Jaguars (2-8)": "Falcons",
  //     "Chargers (6-4) @ Broncos (5-5)": "Broncos",
  //     "Rams (7-3) @ Packers (8-3)": "Rams",
  //     "Vikings (5-5) @ 49ers (5-5)": "49ers",
  //     "Browns (6-5) @ Ravens (7-3)": "Ravens",
  //     "Seahawks (3-7) @ Washington (4-6)": "Washington",
  //     "Seahawks @ Washington Point Total": 55,
  //     Timestamp: "11/25/2021 2:26:17",
  //     "Email Address": "dannysorto1@icloud.com",
  //   },
  //   {
  //     username: "Romero",
  //     "Bears (3-7) @ Lions (0-9-1)": "Bears",
  //     "Raiders (5-5) @ Cowboys (7-3)": "Cowboys",
  //     "Bills (6-4) @ Saints (5-5)": "Bills",
  //     "Buccaneers (7-3) @ Colts (6-5)": "Buccaneers",
  //     "Jets (2-8) @ Texans (2-8)": "Texans",
  //     "Eagles (5-6) @ Giants (3-7)": "Giants",
  //     "Panthers (5-6) @ Dolphins (4-7)": "Dolphins",
  //     "Titans (8-3) @ Patriots (7-4)": "Patriots",
  //     "Steelers (5-4-1) @ Bengals (6-4)": "Bengals",
  //     "Falcons (4-6) @ Jaguars (2-8)": "Jaguars",
  //     "Chargers (6-4) @ Broncos (5-5)": "Chargers",
  //     "Rams (7-3) @ Packers (8-3)": "Rams",
  //     "Vikings (5-5) @ 49ers (5-5)": "Vikings",
  //     "Browns (6-5) @ Ravens (7-3)": "Ravens",
  //     "Seahawks (3-7) @ Washington (4-6)": "Washington",
  //     "Seahawks @ Washington Point Total": 45,
  //     Timestamp: "11/25/2021 11:46:57",
  //     "Email Address": "oscarromero97@gmail.com",
  //   },
  //   {
  //     username: "Walter Market",
  //     "Bears (3-7) @ Lions (0-9-1)": "Lions",
  //     "Raiders (5-5) @ Cowboys (7-3)": "Raiders",
  //     "Bills (6-4) @ Saints (5-5)": "Bills",
  //     "Buccaneers (7-3) @ Colts (6-5)": "Buccaneers",
  //     "Jets (2-8) @ Texans (2-8)": "Texans",
  //     "Eagles (5-6) @ Giants (3-7)": "Eagles",
  //     "Panthers (5-6) @ Dolphins (4-7)": "Panthers",
  //     "Titans (8-3) @ Patriots (7-4)": "Patriots",
  //     "Steelers (5-4-1) @ Bengals (6-4)": "Bengals",
  //     "Falcons (4-6) @ Jaguars (2-8)": "Falcons",
  //     "Chargers (6-4) @ Broncos (5-5)": "Chargers",
  //     "Rams (7-3) @ Packers (8-3)": "Rams",
  //     "Vikings (5-5) @ 49ers (5-5)": "49ers",
  //     "Browns (6-5) @ Ravens (7-3)": "Ravens",
  //     "Seahawks (3-7) @ Washington (4-6)": "Washington",
  //     "Seahawks @ Washington Point Total": 49,
  //     Timestamp: "11/25/2021 10:32:37",
  //     "Email Address": "camoya@icloud.com",
  //   },
  //   {
  //     username: "Lou",
  //     "Bears (3-7) @ Lions (0-9-1)": "Lions",
  //     "Raiders (5-5) @ Cowboys (7-3)": "Cowboys",
  //     "Bills (6-4) @ Saints (5-5)": "Bills",
  //     "Buccaneers (7-3) @ Colts (6-5)": "Buccaneers",
  //     "Jets (2-8) @ Texans (2-8)": "Texans",
  //     "Eagles (5-6) @ Giants (3-7)": "Eagles",
  //     "Panthers (5-6) @ Dolphins (4-7)": "Panthers",
  //     "Titans (8-3) @ Patriots (7-4)": "Patriots",
  //     "Steelers (5-4-1) @ Bengals (6-4)": "Bengals",
  //     "Falcons (4-6) @ Jaguars (2-8)": "Falcons",
  //     "Chargers (6-4) @ Broncos (5-5)": "Chargers",
  //     "Rams (7-3) @ Packers (8-3)": "Packers",
  //     "Vikings (5-5) @ 49ers (5-5)": "Vikings",
  //     "Browns (6-5) @ Ravens (7-3)": "Ravens",
  //     "Seahawks (3-7) @ Washington (4-6)": "Washington",
  //     "Seahawks @ Washington Point Total": 48,
  //     Timestamp: "11/25/2021 6:50:28",
  //     "Email Address": "l14_dc@hotmail.com",
  //   },
  //   {
  //     username: "$link",
  //     "Bears (3-7) @ Lions (0-9-1)": "Bears",
  //     "Raiders (5-5) @ Cowboys (7-3)": "Raiders",
  //     "Bills (6-4) @ Saints (5-5)": "Bills",
  //     "Buccaneers (7-3) @ Colts (6-5)": "Colts",
  //     "Jets (2-8) @ Texans (2-8)": "Texans",
  //     "Eagles (5-6) @ Giants (3-7)": "Eagles",
  //     "Panthers (5-6) @ Dolphins (4-7)": "Panthers",
  //     "Titans (8-3) @ Patriots (7-4)": "Patriots",
  //     "Steelers (5-4-1) @ Bengals (6-4)": "Bengals",
  //     "Falcons (4-6) @ Jaguars (2-8)": "Jaguars",
  //     "Chargers (6-4) @ Broncos (5-5)": "Broncos",
  //     "Rams (7-3) @ Packers (8-3)": "Rams",
  //     "Vikings (5-5) @ 49ers (5-5)": "Vikings",
  //     "Browns (6-5) @ Ravens (7-3)": "Ravens",
  //     "Seahawks (3-7) @ Washington (4-6)": "Seahawks",
  //     "Seahawks @ Washington Point Total": 46,
  //     Timestamp: "11/25/2021 10:57:55",
  //     "Email Address": "kssjimenez@gmail.com",
  //   },
  //   {
  //     username: "Boom x7",
  //     "Bears (3-7) @ Lions (0-9-1)": "Lions",
  //     "Raiders (5-5) @ Cowboys (7-3)": "Raiders",
  //     "Bills (6-4) @ Saints (5-5)": "Bills",
  //     "Buccaneers (7-3) @ Colts (6-5)": "Buccaneers",
  //     "Jets (2-8) @ Texans (2-8)": "Texans",
  //     "Eagles (5-6) @ Giants (3-7)": "Eagles",
  //     "Panthers (5-6) @ Dolphins (4-7)": "Panthers",
  //     "Titans (8-3) @ Patriots (7-4)": "Patriots",
  //     "Steelers (5-4-1) @ Bengals (6-4)": "Steelers",
  //     "Falcons (4-6) @ Jaguars (2-8)": "Falcons",
  //     "Chargers (6-4) @ Broncos (5-5)": "Chargers",
  //     "Rams (7-3) @ Packers (8-3)": "Rams",
  //     "Vikings (5-5) @ 49ers (5-5)": "Vikings",
  //     "Browns (6-5) @ Ravens (7-3)": "Ravens",
  //     "Seahawks (3-7) @ Washington (4-6)": "Washington",
  //     "Seahawks @ Washington Point Total": 47,
  //     Timestamp: "11/25/2021 10:02:32",
  //     "Email Address": "j.martinezmelgar@yahoo.com",
  //   },
  //   {
  //     username: "TMoney",
  //     "Bears (3-7) @ Lions (0-9-1)": "Lions",
  //     "Raiders (5-5) @ Cowboys (7-3)": "Cowboys",
  //     "Bills (6-4) @ Saints (5-5)": "Bills",
  //     "Buccaneers (7-3) @ Colts (6-5)": "Buccaneers",
  //     "Jets (2-8) @ Texans (2-8)": "Texans",
  //     "Eagles (5-6) @ Giants (3-7)": "Eagles",
  //     "Panthers (5-6) @ Dolphins (4-7)": "Panthers",
  //     "Titans (8-3) @ Patriots (7-4)": "Patriots",
  //     "Steelers (5-4-1) @ Bengals (6-4)": "Steelers",
  //     "Falcons (4-6) @ Jaguars (2-8)": "Falcons",
  //     "Chargers (6-4) @ Broncos (5-5)": "Chargers",
  //     "Rams (7-3) @ Packers (8-3)": "Packers",
  //     "Vikings (5-5) @ 49ers (5-5)": "Vikings",
  //     "Browns (6-5) @ Ravens (7-3)": "Ravens",
  //     "Seahawks (3-7) @ Washington (4-6)": "Washington",
  //     "Seahawks @ Washington Point Total": 48,
  //     Timestamp: "11/25/2021 7:23:19",
  //     "Email Address": "earojas003@gmail.com",
  //   },
  //   {
  //     username: "SEL",
  //     "Bears (3-7) @ Lions (0-9-1)": "Lions",
  //     "Raiders (5-5) @ Cowboys (7-3)": "Cowboys",
  //     "Bills (6-4) @ Saints (5-5)": "Saints",
  //     "Buccaneers (7-3) @ Colts (6-5)": "Colts",
  //     "Jets (2-8) @ Texans (2-8)": "Jets",
  //     "Eagles (5-6) @ Giants (3-7)": "Eagles",
  //     "Panthers (5-6) @ Dolphins (4-7)": "Dolphins",
  //     "Titans (8-3) @ Patriots (7-4)": "Titans",
  //     "Steelers (5-4-1) @ Bengals (6-4)": "Bengals",
  //     "Falcons (4-6) @ Jaguars (2-8)": "Jaguars",
  //     "Chargers (6-4) @ Broncos (5-5)": "Chargers",
  //     "Rams (7-3) @ Packers (8-3)": "Rams",
  //     "Vikings (5-5) @ 49ers (5-5)": "Vikings",
  //     "Browns (6-5) @ Ravens (7-3)": "Browns",
  //     "Seahawks (3-7) @ Washington (4-6)": "Washington",
  //     "Seahawks @ Washington Point Total": 42,
  //     Timestamp: "11/25/2021 1:19:29",
  //     "Email Address": "selwinm@yahoo.com",
  //   },
  // ];

  // const week_12_form_submissions_table = [
  //   {
  //     game: "Bears (3-7) @ Lions (0-9-1)",
  //     Jay: "Bears",
  //     Henrock: "Bears",
  //     Odoylerules: "Bears",
  //     Romero: "Bears",
  //     "Walter Market": "Lions",
  //     Lou: "Lions",
  //     $link: "Bears",
  //     "Boom x7": "Lions",
  //     TMoney: "Lions",
  //     SEL: "Lions",
  //   },
  //   {
  //     game: "Raiders (5-5) @ Cowboys (7-3)",
  //     Jay: "Raiders",
  //     Henrock: "Raiders",
  //     Odoylerules: "Cowboys",
  //     Romero: "Cowboys",
  //     "Walter Market": "Raiders",
  //     Lou: "Cowboys",
  //     $link: "Raiders",
  //     "Boom x7": "Raiders",
  //     TMoney: "Cowboys",
  //     SEL: "Cowboys",
  //   },
  //   {
  //     game: "Bills (6-4) @ Saints (5-5)",
  //     Jay: "Bills",
  //     Henrock: "Bills",
  //     Odoylerules: "Bills",
  //     Romero: "Bills",
  //     "Walter Market": "Bills",
  //     Lou: "Bills",
  //     $link: "Bills",
  //     "Boom x7": "Bills",
  //     TMoney: "Bills",
  //     SEL: "Saints",
  //   },
  //   {
  //     game: "Buccaneers (7-3) @ Colts (6-5)",
  //     Jay: "Buccaneers",
  //     Henrock: "Colts",
  //     Odoylerules: "Buccaneers",
  //     Romero: "Buccaneers",
  //     "Walter Market": "Buccaneers",
  //     Lou: "Buccaneers",
  //     $link: "Colts",
  //     "Boom x7": "Buccaneers",
  //     TMoney: "Buccaneers",
  //     SEL: "Colts",
  //   },
  //   {
  //     game: "Jets (2-8) @ Texans (2-8)",
  //     Jay: "Texans",
  //     Henrock: "Texans",
  //     Odoylerules: "Texans",
  //     Romero: "Texans",
  //     "Walter Market": "Texans",
  //     Lou: "Texans",
  //     $link: "Texans",
  //     "Boom x7": "Texans",
  //     TMoney: "Texans",
  //     SEL: "Jets",
  //   },
  //   {
  //     game: "Eagles (5-6) @ Giants (3-7)",
  //     Jay: "Eagles",
  //     Henrock: "Eagles",
  //     Odoylerules: "Eagles",
  //     Romero: "Giants",
  //     "Walter Market": "Eagles",
  //     Lou: "Eagles",
  //     $link: "Eagles",
  //     "Boom x7": "Eagles",
  //     TMoney: "Eagles",
  //     SEL: "Eagles",
  //   },
  //   {
  //     game: "Panthers (5-6) @ Dolphins (4-7)",
  //     Jay: "Panthers",
  //     Henrock: "Dolphins",
  //     Odoylerules: "Panthers",
  //     Romero: "Dolphins",
  //     "Walter Market": "Panthers",
  //     Lou: "Panthers",
  //     $link: "Panthers",
  //     "Boom x7": "Panthers",
  //     TMoney: "Panthers",
  //     SEL: "Dolphins",
  //   },
  //   {
  //     game: "Titans (8-3) @ Patriots (7-4)",
  //     Jay: "Patriots",
  //     Henrock: "Titans",
  //     Odoylerules: "Patriots",
  //     Romero: "Patriots",
  //     "Walter Market": "Patriots",
  //     Lou: "Patriots",
  //     $link: "Patriots",
  //     "Boom x7": "Patriots",
  //     TMoney: "Patriots",
  //     SEL: "Titans",
  //   },
  //   {
  //     game: "Steelers (5-4-1) @ Bengals (6-4)",
  //     Jay: "Steelers",
  //     Henrock: "Bengals",
  //     Odoylerules: "Steelers",
  //     Romero: "Bengals",
  //     "Walter Market": "Bengals",
  //     Lou: "Bengals",
  //     $link: "Bengals",
  //     "Boom x7": "Steelers",
  //     TMoney: "Steelers",
  //     SEL: "Bengals",
  //   },
  //   {
  //     game: "Falcons (4-6) @ Jaguars (2-8)",
  //     Jay: "Falcons",
  //     Henrock: "Falcons",
  //     Odoylerules: "Falcons",
  //     Romero: "Jaguars",
  //     "Walter Market": "Falcons",
  //     Lou: "Falcons",
  //     $link: "Jaguars",
  //     "Boom x7": "Falcons",
  //     TMoney: "Falcons",
  //     SEL: "Jaguars",
  //   },
  //   {
  //     game: "Chargers (6-4) @ Broncos (5-5)",
  //     Jay: "Chargers",
  //     Henrock: "Chargers",
  //     Odoylerules: "Broncos",
  //     Romero: "Chargers",
  //     "Walter Market": "Chargers",
  //     Lou: "Chargers",
  //     $link: "Broncos",
  //     "Boom x7": "Chargers",
  //     TMoney: "Chargers",
  //     SEL: "Chargers",
  //   },
  //   {
  //     game: "Rams (7-3) @ Packers (8-3)",
  //     Jay: "Packers",
  //     Henrock: "Packers",
  //     Odoylerules: "Rams",
  //     Romero: "Rams",
  //     "Walter Market": "Rams",
  //     Lou: "Packers",
  //     $link: "Rams",
  //     "Boom x7": "Rams",
  //     TMoney: "Packers",
  //     SEL: "Rams",
  //   },
  //   {
  //     game: "Vikings (5-5) @ 49ers (5-5)",
  //     Jay: "49ers",
  //     Henrock: "Vikings",
  //     Odoylerules: "49ers",
  //     Romero: "Vikings",
  //     "Walter Market": "49ers",
  //     Lou: "Vikings",
  //     $link: "Vikings",
  //     "Boom x7": "Vikings",
  //     TMoney: "Vikings",
  //     SEL: "Vikings",
  //   },
  //   {
  //     game: "Browns (6-5) @ Ravens (7-3)",
  //     Jay: "Ravens",
  //     Henrock: "Ravens",
  //     Odoylerules: "Ravens",
  //     Romero: "Ravens",
  //     "Walter Market": "Ravens",
  //     Lou: "Ravens",
  //     $link: "Ravens",
  //     "Boom x7": "Ravens",
  //     TMoney: "Ravens",
  //     SEL: "Browns",
  //   },
  //   {
  //     game: "Seahawks (3-7) @ Washington (4-6)",
  //     Jay: "Washington",
  //     Henrock: "Washington",
  //     Odoylerules: "Washington",
  //     Romero: "Washington",
  //     "Walter Market": "Washington",
  //     Lou: "Washington",
  //     $link: "Seahawks",
  //     "Boom x7": "Washington",
  //     TMoney: "Washington",
  //     SEL: "Washington",
  //   },
  //   {
  //     "Point Total": "Seahawks @ Washington Point Total",
  //     Jay: "45",
  //     Henrock: "38",
  //     Odoylerules: "55",
  //     Romero: "45",
  //     "Walter Market": "49",
  //     Lou: "48",
  //     $link: "46",
  //     "Boom x7": "47",
  //     TMoney: "48",
  //     SEL: "42",
  //   },
  //   {
  //     final: "Total Ls",
  //     Jay: "5",
  //     Henrock: "6",
  //     Odoylerules: "6",
  //     Romero: "6",
  //     "Walter Market": "6",
  //     Lou: "7",
  //     $link: "8",
  //     "Boom x7": "8",
  //     TMoney: "8",
  //     SEL: "11",
  //   },
  // ];

  // for (let k = 0; k < week_12_form_submissions_table.length; k++) {
  //   firebase
  //     .firestore()
  //     .collection("season_2021")
  //     .doc("week_12")
  //     .collection("form_submissions_table")
  //     .add(week_12_form_submissions_table[k]);
  // }
}
